In [27]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [3]:
df = pd.read_pickle('../../Machine Learning/Data Incubator/nyc_collisions_cat.pkl')

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1491922 entries, 0 to 1491921
Columns: 358 entries, NUMBER OF PERSONS INJURED to vehicle_fire
dtypes: int64(9), uint8(349)
memory usage: 599.0 MB

In [6]:
df

,NUMBER OF PERSONS INJURED,NUMBER OF PERSONS KILLED,NUMBER OF PEDESTRIANS INJURED,NUMBER OF PEDESTRIANS KILLED,NUMBER OF CYCLIST INJURED,NUMBER OF CYCLIST KILLED,NUMBER OF MOTORIST INJURED,NUMBER OF MOTORIST KILLED,CRASH_HR_0,CRASH_HR_1,...,vehicle_sedan,vehicle_taxi,vehicle_truck,vehicle_pick-up,vehicle_bus,vehicle_motorcycle,vehicle_bike,vehicle_tractor,vehicle_ambulance,vehicle_fire
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,2,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1491917,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1491918,1,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1491919,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1491920,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1491921,1,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,1,0,0,0,0

In [34]:
column_names = df.columns.values

In [36]:
del df

In [12]:
X = df.loc[:,'CRASH_HR_0':].values

In [15]:
X.shape

(1491922, 350)

In [29]:
y = df.loc[:,:'NUMBER OF MOTORIST KILLED'].values

In [30]:
y.shape

(1491922, 8)

In [31]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [38]:
reg = LinearRegression().fit(X_train, y_train)

In [44]:
y_pred = reg.predict(X_test)

In [55]:
y_pred[9]

array([ 3.59741211e-01,  1.27208233e-03,  7.61108398e-02,  8.71062279e-04,
        1.50756836e-02,  6.97523355e-04,  2.69165039e-01, -2.97069550e-04])